---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cqdjyhrb/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp -R webfonts assets css js $DEPLOYPATH
    